version: '3.4'

services:
  techchalenge.restaurante:
    image: ${DOCKER_REGISTRY-}techchalengerestaurante
    build:
      context: .
      dockerfile: src/Adapter/Driver/Restaurant.Api/Dockerfile
    ports:
      - "5000:80"
