version: '3.6'

networks:
  tech_challenge:

services: 
    db:
        container_name: mysql_tc
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: TechChallenge#2023
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "3306:3306"
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        networks:
            - tech_challenge
    api:
        image: ${DOCKER_REGISTRY-}api
        build:
            context: .
            dockerfile: ../TechChalenge.Restaurante/Dockerfile
        ports:
            - "15000:80"
        networks:
            - tech_challenge
        depends_on:
            - "db"



